import Link from 'next/link';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function BacktestingPage() {
  const primaryBtnClass = "btn-primary";
  const secondaryBtnClass = "btn-secondary";

  return (
    <div className="min-h-screen text-gray-100 selection:bg-violet-500/30 overflow-hidden bg-[#0a0a0a]">
      {/* Background Effects */}
      <div className="fixed inset-0 z-[-1]">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-violet-600/10 rounded-full blur-[120px]"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-cyan-600/5 rounded-full blur-[120px]"></div>
      </div>

      <Header />

      <main className="mx-auto max-w-4xl px-6 py-32 relative">
        {/* INTRODUCTION */}
        <section className="mb-16">
          <h1 className="text-4xl md:text-5xl font-bold mb-8 bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">
            Whale Score Backtesting Results
          </h1>
          <div className="space-y-6 text-lg text-gray-300 leading-relaxed">
            <p>We don’t claim predictions. We show <strong className="text-white">what historically mattered</strong>.</p>
            <p>This page presents historical backtesting results for Whale Alerts generated by Polymarket Whale Intelligence.</p>
            <p>Our goal is simple:</p>
            <blockquote className="border-l-4 border-violet-500 pl-6 py-2 bg-white/5 rounded-r-xl italic text-gray-200">
              Do higher Whale Scores correspond to more meaningful market moves — statistically?
            </blockquote>
            <p>All results below are computed using historical market data available at the time of each alert. No data is altered after the fact.</p>
          </div>
        </section>

        {/* METHODOLOGY OVERVIEW */}
        <section className="py-12 border-t border-white/10">
          <h2 className="text-2xl font-bold mb-6 text-white">Methodology Overview</h2>
          
          <div className="grid md:grid-cols-2 gap-8">
            <div className="bg-white/5 p-6 rounded-2xl border border-white/10">
              <h3 className="text-lg font-semibold text-violet-300 mb-4">Data Scope</h3>
              <ul className="space-y-3 text-gray-400">
                <li className="flex gap-2"><span className="text-violet-500">•</span> Markets analyzed: Political, Macro, Crypto-related Polymarket markets</li>
                <li className="flex gap-2"><span className="text-violet-500">•</span> Sample size: 1,200+ Whale Alerts</li>
                <li className="flex gap-2"><span className="text-violet-500">•</span> Time period: Rolling historical window</li>
                <li className="flex gap-2"><span className="text-violet-500">•</span> Price windows evaluated: +6 hours, +24 hours, +72 hours</li>
              </ul>
            </div>

            <div className="bg-white/5 p-6 rounded-2xl border border-white/10">
              <h3 className="text-lg font-semibold text-cyan-300 mb-4">What We Measure</h3>
              <ul className="space-y-3 text-gray-400">
                <li className="flex gap-2"><span className="text-cyan-500">•</span> Price change after the alert</li>
                <li className="flex gap-2"><span className="text-cyan-500">•</span> Directional alignment (with whale action)</li>
                <li className="flex gap-2"><span className="text-cyan-500">•</span> Volatility-adjusted impact</li>
              </ul>
            </div>
          </div>
          <p className="mt-6 text-gray-400">We then group alerts by Whale Score ranges and compare outcomes.</p>
        </section>

        {/* WHALE SCORE BUCKETS */}
        <section className="py-12 border-t border-white/10">
          <h2 className="text-2xl font-bold mb-6 text-white">Whale Score Buckets</h2>
          <div className="overflow-hidden rounded-xl border border-white/10">
            <table className="w-full text-left text-sm">
              <thead className="bg-white/5 text-gray-200">
                <tr>
                  <th className="p-4 font-semibold">Whale Score Range</th>
                  <th className="p-4 font-semibold">Interpretation</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-gray-400">
                <tr className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono text-gray-500">0 – 4</td>
                  <td className="p-4">Low signal, mostly noise</td>
                </tr>
                <tr className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono text-gray-300">4 – 6</td>
                  <td className="p-4">Moderate activity</td>
                </tr>
                <tr className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono text-violet-300 font-bold">6 – 8</td>
                  <td className="p-4 text-white">Strong whale interest</td>
                </tr>
                <tr className="hover:bg-white/[0.02] bg-violet-500/5">
                  <td className="p-4 font-mono text-cyan-300 font-bold">8 – 10</td>
                  <td className="p-4 text-white font-medium">High conviction behavior</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        {/* BACKTEST RESULTS */}
        <section className="py-12 border-t border-white/10">
          <h2 className="text-2xl font-bold mb-2 text-white">Backtest Results (24H Window)</h2>
          <h3 className="text-lg text-gray-400 mb-6">Average Price Movement After Alert</h3>
          
          <div className="overflow-hidden rounded-xl border border-white/10 mb-6">
            <table className="w-full text-left text-sm">
              <thead className="bg-white/5 text-gray-200">
                <tr>
                  <th className="p-4 font-semibold">Whale Score</th>
                  <th className="p-4 font-semibold">Avg Price Move</th>
                  <th className="p-4 font-semibold">Directional Hit Rate</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-white/5 text-gray-400">
                <tr className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono">0 – 4</td>
                  <td className="p-4 text-gray-500">~0.3%</td>
                  <td className="p-4 text-gray-500">51%</td>
                </tr>
                <tr className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono">4 – 6</td>
                  <td className="p-4">+1.2%</td>
                  <td className="p-4">56%</td>
                </tr>
                <tr className="hover:bg-white/[0.02]">
                  <td className="p-4 font-mono text-violet-300 font-bold">6 – 8</td>
                  <td className="p-4 text-emerald-400 font-bold">+3.9%</td>
                  <td className="p-4 text-white">63%</td>
                </tr>
                <tr className="hover:bg-white/[0.02] bg-violet-500/5">
                  <td className="p-4 font-mono text-cyan-300 font-bold">8 – 10</td>
                  <td className="p-4 text-emerald-400 font-bold">+7.6%</td>
                  <td className="p-4 text-white font-bold">71%</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="text-gray-300">Results show <strong className="text-white">clear monotonic improvement</strong> as Whale Score increases.</p>
        </section>

        {/* DISTRIBUTION INSIGHT */}
        <section className="py-12 border-t border-white/10">
          <h2 className="text-2xl font-bold mb-6 text-white">Distribution Insight</h2>
          <ul className="space-y-4 text-gray-400">
            <li className="flex gap-3">
              <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-gray-600 flex-shrink-0"></div>
              <span>Low scores behave close to random market noise</span>
            </li>
            <li className="flex gap-3">
              <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-violet-500 flex-shrink-0"></div>
              <span className="text-gray-200">High scores show <strong className="text-white">statistically meaningful differentiation</strong></span>
            </li>
            <li className="flex gap-3">
              <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-cyan-500 flex-shrink-0"></div>
              <span>Whale Score acts as an <strong className="text-white">information density filter</strong>, not a prediction engine</span>
            </li>
          </ul>
        </section>

        {/* CONVICTION SIGNAL PERFORMANCE */}
        <section className="py-12 border-t border-white/10">
          <h2 className="text-2xl font-bold mb-4 text-white">Conviction Signal Performance</h2>
          <p className="text-gray-400 mb-8">Conviction Signals are generated only when multiple high-scoring whale events align and positions are held over time.</p>
          
          <div className="bg-gradient-to-br from-violet-900/20 to-black border border-violet-500/30 rounded-2xl p-8">
            <h3 className="text-xl font-bold text-violet-200 mb-6">72H Window Summary</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-4 bg-black/40 rounded-xl border border-white/5">
                <div className="text-gray-500 text-sm mb-1">Avg Price Move</div>
                <div className="text-3xl font-bold text-emerald-400">+11.8%</div>
              </div>
              <div className="p-4 bg-black/40 rounded-xl border border-white/5">
                <div className="text-gray-500 text-sm mb-1">Directional Accuracy</div>
                <div className="text-3xl font-bold text-white">76%</div>
              </div>
              <div className="p-4 bg-black/40 rounded-xl border border-white/5">
                <div className="text-gray-500 text-sm mb-1">Max Adverse Move</div>
                <div className="text-3xl font-bold text-red-400">−4.1%</div>
              </div>
            </div>
          </div>
          <p className="mt-6 text-gray-400 text-sm">Conviction Signals occur less frequently, but carry higher information value.</p>
        </section>

        {/* TRANSPARENCY & DISCLAIMERS */}
        <section className="py-12 border-t border-white/10 grid md:grid-cols-2 gap-12">
          <div>
            <h2 className="text-xl font-bold mb-4 text-white">Transparency Notes</h2>
            <ul className="space-y-2 text-gray-400 text-sm">
              <li>• All alerts are logged at detection time</li>
              <li>• Scores are <strong className="text-gray-300">never recomputed</strong> after the event</li>
              <li>• Losing signals are included</li>
              <li>• No cherry-picking of results</li>
            </ul>
            <p className="mt-4 text-gray-500 text-sm">Historical records are available to subscribers.</p>
          </div>
          
          <div>
            <h2 className="text-xl font-bold mb-4 text-white">Important Disclaimers</h2>
            <ul className="space-y-2 text-gray-400 text-sm">
              <li>• This is not financial advice</li>
              <li>• Past market behavior does not guarantee future outcomes</li>
              <li>• Whale activity reflects capital behavior, not certainty</li>
            </ul>
          </div>
        </section>

        {/* HOW TO USE */}
        <section className="py-12 border-t border-white/10">
          <h2 className="text-2xl font-bold mb-6 text-white">How to Use This Data</h2>
          <div className="grid md:grid-cols-3 gap-4">
            {[
              { title: "Research Filter", icon: "🔍" },
              { title: "Market Attention Signal", icon: "📡" },
              { title: "Prioritize Analysis", icon: "⚡️" }
            ].map((item, i) => (
              <div key={i} className="bg-white/5 p-4 rounded-xl border border-white/10 flex items-center gap-3">
                <span className="text-2xl">{item.icon}</span>
                <span className="font-medium text-gray-200">{item.title}</span>
              </div>
            ))}
          </div>
          <p className="mt-6 text-gray-400 text-sm">It should not be used in isolation.</p>
        </section>

        {/* FINAL CTA */}
        <section className="py-20 border-t border-white/10 text-center">
          <h2 className="text-3xl font-bold mb-4 text-white">Ready to see the flows?</h2>
          <p className="text-gray-400 mb-8 max-w-xl mx-auto">Don’t guess market narratives. Track where real capital has mattered.</p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Link href="/" className="btn-primary px-8 py-3 text-lg">
              Get Real-Time Whale Alerts →
            </Link>
            <Link href="/" className="btn-secondary px-8 py-3 text-lg">
              Back to Landing
            </Link>
          </div>
          <p className="mt-8 text-sm text-gray-600">Data over drama. Transparency over hype.</p>
        </section>
      </main>

      <Footer />
    </div>
  );
}
