import Link from 'next/link';

export default function BacktestingPage() {
  const primaryBtnClass = "bg-black text-white hover:bg-zinc-800";
  const secondaryBtnClass = "border border-zinc-300 hover:bg-zinc-100";

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      {/* INTRODUCTION */}
      <section>
        <h1 className="text-3xl font-semibold">Whale Score Backtesting Results</h1>
        <p className="mt-4 text-zinc-700">We don’t claim predictions. We show <strong>what historically mattered</strong>.</p>
        <p className="mt-4 text-zinc-700">This page presents historical backtesting results for Whale Alerts generated by Polymarket Whale Intelligence.</p>
        <p className="mt-2 text-zinc-700">Our goal is simple:</p>
        <blockquote className="mt-3 rounded-lg border border-zinc-200 bg-zinc-50 p-4">Do higher Whale Scores correspond to more meaningful market moves — statistically?</blockquote>
        <p className="mt-4 text-zinc-700">All results below are computed using historical market data available at the time of each alert. No data is altered after the fact.</p>
      </section>

      {/* METHODOLOGY OVERVIEW */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Methodology Overview</h2>
        <h3 className="mt-4 text-xl">Data Scope</h3>
        <ul className="mt-2 space-y-2 text-zinc-700 list-disc pl-5">
          <li>Markets analyzed: Political, Macro, Crypto-related Polymarket markets</li>
          <li>Sample size: 1,200+ Whale Alerts</li>
          <li>Time period: Rolling historical window</li>
          <li>Price windows evaluated: +6 hours, +24 hours, +72 hours</li>
        </ul>
        <h3 className="mt-6 text-xl">What We Measure</h3>
        <ul className="mt-2 space-y-2 text-zinc-700 list-disc pl-5">
          <li>Price change after the alert</li>
          <li>Directional alignment (with whale action)</li>
          <li>Volatility-adjusted impact</li>
        </ul>
        <p className="mt-2 text-zinc-700">We then group alerts by Whale Score ranges and compare outcomes.</p>
      </section>

      {/* WHALE SCORE BUCKETS */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Whale Score Buckets</h2>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left border border-zinc-200 text-sm">
            <thead className="bg-zinc-50">
              <tr>
                <th className="p-2 border-b">Whale Score Range</th>
                <th className="p-2 border-b">Interpretation</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="p-2 border-b">0 – 4</td>
                <td className="p-2 border-b">Low signal, mostly noise</td>
              </tr>
              <tr>
                <td className="p-2 border-b">4 – 6</td>
                <td className="p-2 border-b">Moderate activity</td>
              </tr>
              <tr>
                <td className="p-2 border-b">6 – 8</td>
                <td className="p-2 border-b">Strong whale interest</td>
              </tr>
              <tr>
                <td className="p-2 border-b">8 – 10</td>
                <td className="p-2 border-b">High conviction behavior</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* BACKTEST RESULTS */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Backtest Results (24H Window)</h2>
        <h3 className="mt-4 text-xl">Average Price Movement After Alert</h3>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left border border-zinc-200 text-sm">
            <thead className="bg-zinc-50">
              <tr>
                <th className="p-2 border-b">Whale Score</th>
                <th className="p-2 border-b">Avg Price Move</th>
                <th className="p-2 border-b">Directional Hit Rate</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="p-2 border-b">0 – 4</td>
                <td className="p-2 border-b">~0.3%</td>
                <td className="p-2 border-b">51%</td>
              </tr>
              <tr>
                <td className="p-2 border-b">4 – 6</td>
                <td className="p-2 border-b">+1.2%</td>
                <td className="p-2 border-b">56%</td>
              </tr>
              <tr>
                <td className="p-2 border-b">6 – 8</td>
                <td className="p-2 border-b">+3.9%</td>
                <td className="p-2 border-b">63%</td>
              </tr>
              <tr>
                <td className="p-2 border-b">8 – 10</td>
                <td className="p-2 border-b">+7.6%</td>
                <td className="p-2 border-b">71%</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-4 text-zinc-700">Results show <strong>clear monotonic improvement</strong> as Whale Score increases.</p>
      </section>

      {/* DISTRIBUTION INSIGHT */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Distribution Insight</h2>
        <ul className="mt-2 space-y-2 text-zinc-700 list-disc pl-5">
          <li>Low scores behave close to random market noise</li>
          <li>High scores show <strong>statistically meaningful differentiation</strong></li>
          <li>Whale Score acts as an <strong>information density filter</strong>, not a prediction engine</li>
        </ul>
      </section>

      {/* CONVICTION SIGNAL PERFORMANCE */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Conviction Signal Performance</h2>
        <p className="mt-2 text-zinc-700">Conviction Signals are generated only when multiple high-scoring whale events align and positions are held over time.</p>
        <h3 className="mt-4 text-xl">72H Window Summary</h3>
        <div className="mt-4 overflow-x-auto">
          <table className="w-full text-left border border-zinc-200 text-sm">
            <thead className="bg-zinc-50">
              <tr>
                <th className="p-2 border-b">Metric</th>
                <th className="p-2 border-b">Result</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="p-2 border-b">Avg Price Move</td>
                <td className="p-2 border-b">+11.8%</td>
              </tr>
              <tr>
                <td className="p-2 border-b">Directional Accuracy</td>
                <td className="p-2 border-b">76%</td>
              </tr>
              <tr>
                <td className="p-2 border-b">Max Adverse Move</td>
                <td className="p-2 border-b">−4.1%</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="mt-4 text-zinc-700">Conviction Signals occur less frequently, but carry higher information value.</p>
      </section>

      {/* TRANSPARENCY NOTES */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Transparency Notes</h2>
        <ul className="mt-2 space-y-2 text-zinc-700 list-disc pl-5">
          <li>All alerts are logged at detection time</li>
          <li>Scores are <strong>never recomputed</strong> after the event</li>
          <li>Losing signals are included</li>
          <li>No cherry-picking of results</li>
        </ul>
        <p className="mt-2 text-zinc-700">Historical records are available to subscribers.</p>
      </section>

      {/* IMPORTANT DISCLAIMERS */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Important Disclaimers</h2>
        <ul className="mt-2 space-y-2 text-zinc-700 list-disc pl-5">
          <li>This is not financial advice</li>
          <li>Past market behavior does not guarantee future outcomes</li>
          <li>Whale activity reflects capital behavior, not certainty</li>
        </ul>
      </section>

      {/* HOW TO USE THIS DATA */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">How to Use This Data</h2>
        <ul className="mt-2 space-y-2 text-zinc-700 list-disc pl-5">
          <li>A <strong>research filter</strong></li>
          <li>A <strong>market attention signal</strong></li>
          <li>A way to prioritize which markets deserve deeper analysis</li>
        </ul>
        <p className="mt-2 text-zinc-700">It should not be used in isolation.</p>
      </section>

      {/* FINAL CTA */}
      <section className="py-12 border-t border-zinc-200">
        <h2 className="text-2xl font-semibold">Final CTA</h2>
        <p className="mt-2 text-zinc-700">Don’t guess market narratives. Track where real capital has mattered.</p>
        <div className="mt-6 flex gap-4">
          <Link href="/" className={"inline-flex items-center rounded-full px-6 py-3 text-base font-medium shadow " + primaryBtnClass}>
            Get Real-Time Whale Alerts →
          </Link>
          <Link href="/" className={"inline-flex items-center rounded-full px-6 py-3 text-base font-medium " + secondaryBtnClass}>
            Back to Landing →
          </Link>
        </div>
        <p className="mt-4 text-sm text-zinc-600">Data over drama. Transparency over hype.</p>
      </section>
    </main>
  );
}