import type { BlogPost } from './blog';

/** Daily briefs generated by trade_ingest → `blog_posts` use this slug prefix. */
export function isDailySpotlightSlug(slug: string): boolean {
  return slug.startsWith('daily-spotlight-');
}

/**
 * Parse `daily-spotlight-YYYY-MM-DD` for stable ordering even when `published_at`
 * and other posts' dates would interleave in the global blog sort.
 */
export function spotlightSlugSortKey(slug: string): number {
  const m = /^daily-spotlight-(\d{4}-\d{2}-\d{2})$/.exec(slug);
  if (!m) return Number.NEGATIVE_INFINITY;
  return new Date(`${m[1]}T12:00:00.000Z`).getTime();
}

export function sortDailySpotlightPosts(posts: BlogPost[]): BlogPost[] {
  return [...posts].sort((a, b) => {
    const kb = spotlightSlugSortKey(b.slug);
    const ka = spotlightSlugSortKey(a.slug);
    if (kb !== ka) return kb - ka;
    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });
}

export function newestSpotlightTimestampMs(posts: BlogPost[]): number | null {
  const sorted = sortDailySpotlightPosts(posts.filter((p) => isDailySpotlightSlug(p.slug)));
  if (sorted.length === 0) return null;
  const t = new Date(sorted[0].date).getTime();
  return Number.isFinite(t) ? t : null;
}
